In [10]:
#!pip install numpy

# 🧩 Actividad práctica: NumPy y Pandas
Este notebook incluye ejercicios básicos de **NumPy** y **Pandas** para practicar el análisis de datos.

## 📊 Parte 1: NumPy - Operaciones básicas

### 1️⃣ Crear un array NumPy con 10 números enteros

In [51]:
import numpy as np

array = np.array([25, 4, 18, 20, 1, 12, 14, 9, 6, 8])
array_2d = np.array(
    [
        [1, 2, 3],
        [4, 5, 6,]
    ]
)
print(array)
print(array_2d)

[25  4 18 20  1 12 14  9  6  8]
[[1 2 3]
 [4 5 6]]


### 2️⃣ Mostrar las propiedades del array: dimensión, tipo de dato y forma

In [76]:
print("Propiedades del Array:")
print("Dimensión: ", array.ndim)
print("Tipo de dato: ", array.dtype)
print("Forma: ", array.shape)
print("Tamaño: ", array.size)
print("Dimension 2d:", array_2d.ndim)
# (Cantidad dimensiones, Cantidad de elementos por cada dimensión)
print("Forma 2d: ", array_2d.shape)
print("Tamaño 2d: ", array_2d.size)

Propiedades del Array:
Dimensión:  1
Tipo de dato:  int64
Forma:  (10,)
Tamaño:  10
Dimension 2d: 2
Forma 2d:  (2, 3)
Tamaño 2d:  6


### 3️⃣ Ordenar los valores del array

In [56]:
array.sort()  # in place, modifica la variable ya existente (no devuelve un resultado)
print(array)

[ 1  4  6  8  9 12 14 18 20 25]


### 4️⃣ Calcular el promedio del array

In [59]:
promedio = array.mean()
print("Promedio: ", promedio)

Promedio:  11.7


### 5️⃣ Mostrar el valor máximo y el valor mínimo

In [63]:
maximo = array.max()
minimo = array.min()
print("Valor máximo: ", maximo)
print("Valor mínimo: ", minimo)

Valor máximo:  25
Valor mínimo:  1


In [72]:
array_decimales = np.array([11.5, 55.26, 89.9, 14.5])
print(array_decimales.ndim)
print(array_decimales.shape)
print(array_decimales.dtype)

1
(4,)
float64


In [71]:
# Redondear decimales
array_round = array_decimales.round()
print("Array decimales: ", array_decimales)
print("Array redondeado: ", array_round)

Array decimales:  [11.5  55.26 89.9  14.5 ]
Array redondeado:  [12. 55. 90. 14.]


In [77]:
array_decimales = np.array([11.568, 55.2699, 89.95, 14.511])
array_round_1 = array_decimales.round(1)
print("Array redondeado a 1 decimal: ", array_round_1)

Array redondeado a 1 decimal:  [11.6 55.3 90.  14.5]


## 🐼 Parte 2: Pandas - Dataset *tips*

Usaremos el dataset **tips** de la librería `seaborn`. Este conjunto contiene datos sobre propinas en un restaurante.

In [ ]:
import pandas as pd
import seaborn as sns

tips = sns.load_dataset('tips')

### 1️⃣ Mostrar las primeras 3 filas del dataset

In [ ]:
# Tu código aquí 👇


### 2️⃣ Mostrar las últimas 5 filas del dataset

In [ ]:
# Tu código aquí 👇


### 3️⃣ Calcular la sumatoria total de la columna `tip` (propina)

In [ ]:
# Tu código aquí 👇


### 4️⃣ Calcular el promedio de la cuenta (`total_bill`) de los hombres

In [ ]:
# Tu código aquí 👇


### 5️⃣ Calcular el promedio de la cuenta (`total_bill`) de las mujeres

In [ ]:
# Tu código aquí 👇


### 6️⃣ Calcular el promedio de la cuenta (`total_bill`) de mujeres fumadoras

In [ ]:
# Tu código aquí 👇


### 7️⃣ Calcular la propina promedio (`tip`) de los días sábado y domingo

In [ ]:
# Tu código aquí 👇


### 8️⃣ Filtrar filas donde la propina (`tip`) sea mayor al promedio general de las propinas
💡 Usa `tips['tip'].mean()` para calcular el promedio antes de aplicar el filtro.

In [ ]:
# Calcular el promedio de propinas
promedio_propina = tips['tip'].mean()

# Filtrar filas con propinas mayores al promedio
# Tu código aquí 👇
