# Numpy

In [29]:
import numpy as np

In [30]:
estudiantes = np.array(["Ana", "Luis", "Carlos", "Marta", "Juan"])
calificaciones = np.array([85, 92, 78, 95, 88])

In [31]:
estudiantes = np.array(["Ana", "Luis", "Marta", "Juan"])
materias = np.array(["Matemáticas", "Física", "Química", "Programación", "Inglés"])

# Notas de cada estudiante en cada materia
calificaciones = np.array([
    [85, 92, 78, 95, 88],   # Notas de Ana
    [76, 88, 82, 70, 79],   # Notas de Luis
    [94, 90, 89, 98, 91],   # Notas de Marta
    [80, 75, 72, 85, 81]    # Notas de Juan
])

print("Matriz de calificaciones:")
print(calificaciones)

Matriz de calificaciones:
[[85 92 78 95 88]
 [76 88 82 70 79]
 [94 90 89 98 91]
 [80 75 72 85 81]]


In [32]:
# Ejercicio 2.1: Mostrar las dimensiones (shape) de la matriz calificaciones
print("1. Dimensiones de la matriz:", calificaciones.shape)

1. Dimensiones de la matriz: (4, 5)


In [33]:
# Ejercicio 2.2: Mostrar el nombre del segundo estudiante en la lista
print("2. Segundo estudiante:", estudiantes[1])

2. Segundo estudiante: Luis


In [34]:
# Ejercicio 2.3: Mostrar todas las calificaciones de Marta
print("3. Calificaciones de Marta:", calificaciones[2])

3. Calificaciones de Marta: [94 90 89 98 91]


In [35]:
# Ejercicio 2.4: Mostrar la calificación de Juan en Física
# Juan está en el índice 3, Física está en el índice 1
print("4. Calificación de Juan en Física:", calificaciones[3, 1])

4. Calificación de Juan en Física: 75


In [36]:
# Ejercicio 2.5: Mostrar todas las calificaciones de la materia de Programación
# Programación está en el índice 3 (columna 3)
print("5. Calificaciones de Programación:", calificaciones[:, 3])

5. Calificaciones de Programación: [95 70 98 85]


In [37]:
# Ejercicio 3.1: Mostrar las calificaciones de los dos primeros estudiantes
print("Ejercicio 3.1 - Calificaciones de los dos primeros estudiantes:")
print(calificaciones[0:2])

Ejercicio 3.1 - Calificaciones de los dos primeros estudiantes:
[[85 92 78 95 88]
 [76 88 82 70 79]]


In [38]:
# Ejercicio 3.2: Mostrar las calificaciones de todas las materias excepto Inglés (las primeras 4 columnas)
print("Ejercicio 3.2 - Calificaciones de todas las materias excepto Inglés:")
print(calificaciones[:, 0:4])

Ejercicio 3.2 - Calificaciones de todas las materias excepto Inglés:
[[85 92 78 95]
 [76 88 82 70]
 [94 90 89 98]
 [80 75 72 85]]


In [39]:
# Ejercicio 3.3: Crear una sub-matriz que contenga solo las calificaciones de Marta y Juan 
# en las materias de Química y Programación
# Marta: índice 2, Juan: índice 3
# Química: índice 2, Programación: índice 3
print("Ejercicio 3.3 - Calificaciones de Marta y Juan en Química y Programación:")
sub_matriz = calificaciones[2:, 2:4]
print(sub_matriz)

Ejercicio 3.3 - Calificaciones de Marta y Juan en Química y Programación:
[[89 98]
 [72 85]]


In [60]:
# Ejercicio 4

# Promedio de calificaciones de cada estudiante y muestralo
# axis = 0 --> columnas, axis = 1 --> filas
promedios_estudiantes = np.mean(calificaciones, axis=1)
print(promedios_estudiantes)

[87.6 79.  92.4 78.6]


In [41]:
# promedio de calificaciones de cada materia
promedio_materias = np.mean(calificaciones, axis=0)
print(promedio_materias)

[83.75 86.25 80.25 87.   84.75]


In [42]:
print("Notas de fisica: ", calificaciones[:, 2])

# Obtener la nota máxima de física
maximo_fisica = np.max(calificaciones[:, 1])
print("Nota máxima de física: ", maximo_fisica)

Notas de fisica:  [78 82 89 72]
Nota máxima de física:  92


In [43]:
# Indicar las calificaciones que son mayores a 90
calificaciones_mayores_90 = calificaciones >= 90
print(calificaciones_mayores_90)

[[False  True False  True False]
 [False False False False False]
 [ True  True False  True  True]
 [False False False False False]]


In [44]:
# Mostrar los nombres de los estudiantes que obtuvieron una calificacion menor a 80 en matemáticas
calificaciones_matematicas = calificaciones[:, 0] <= 80 
estudiantes_menor_80 = estudiantes[calificaciones_matematicas]
print(estudiantes_menor_80)

['Luis' 'Juan']


In [47]:
# Mostrar los nombres de las materias en las que Ana obtuvo una calificación superior a 90
calificaciones_ana = calificaciones[0, :] > 90
materias_mayor_90 = materias[calificaciones_ana]
print(materias_mayor_90)

['Física' 'Programación']


In [55]:
# Obtener los nombres de los estudiantes ordenandos de menor a mayor según su calificación en programación
notas_programacion = calificaciones[:, 3]
indices_ordenados = np.argsort(notas_programacion) # Obtener los índices de los elementos ordenados
estudiantes_ordenados = estudiantes[indices_ordenados]
print(estudiantes_ordenados)

['Luis' 'Juan' 'Ana' 'Marta']


In [ ]:
# Para cada estudiante, mostrar el nombre de la materia
# *PENDIENTE
indice_nota_baja = np.argmin(calificaciones, axis=1)

for i in range(len(estudiantes)):
    print(f"El estudiante {estudiantes[i]} tiene su nota más baja en la materia {materias[indice_nota_baja[i]]}")

El estudiante Ana tiene su nota más baja en la materia Química
El estudiante Luis tiene su nota más baja en la materia Programación
El estudiante Marta tiene su nota más baja en la materia Química
El estudiante Juan tiene su nota más baja en la materia Química


# Pandas

In [61]:
import pandas as pd

In [ ]:
# Creando una serie de pandas a partir de una lista
planes = ['Basic', 'Standard', 'Premium']
tipos_planes = pd.Series(planes)
display(tipos_planes)

0       Basic
1    Standard
2     Premium
dtype: object

In [83]:
# Creando una serie de pandas a partir de un diccionario
datos_usuarios = {'Usuario': ['user1', 'user2', 'user3']}
datos_usuarios = pd.Series(datos_usuarios)
display(datos_usuarios)

Usuario    [user1, user2, user3]
dtype: object

In [82]:
# Creando un dataframe de pandas a partir de un diccionario
datos_usuarios = {
    'Usuario': ['User1', 'User2', 'User3'],
    'Edad': [25, 32, 51]
}

df = pd.DataFrame(datos_usuarios)
display(df)

Usuario  Edad
0   User1    25
1   User2    32
2   User3    51

In [84]:
# Crear un dataframe a partir de un archivo csv
df = pd.read_csv('data/netflix_customer_churn.csv')
display(df.head())  # Mostrar los primeros 5 elementos del dataframe

customer_id  age  gender subscription_type  \
0  a9b75100-82a8-427a-a208-72f24052884a   51   Other             Basic   
1  49a5dfd9-7e69-4022-a6ad-0a1b9767fb5b   47   Other          Standard   
2  4d71f6ce-fca9-4ff7-8afa-197ac24de14b   27  Female          Standard   
3  d3c72c38-631b-4f9e-8a0e-de103cad1a7d   53   Other           Premium   
4  4e265c34-103a-4dbb-9553-76c9aa47e946   56   Other          Standard   

   watch_hours  last_login_days   region  device  monthly_fee  churned  \
0        14.73               29   Africa      TV         8.99        1   
1         0.70               19   Europe  Mobile        13.99        1   
2        16.32               10     Asia      TV        13.99        0   
3         4.51               12  Oceania      TV        17.99        1   
4         1.89               13   Africa  Mobile        13.99        1   

  payment_method  number_of_profiles  avg_watch_time_per_day favorite_genre  
0      Gift Card                   1                    0.49         Action  
1      Gift Card                   5                    0.03         Sci-Fi  
2         Crypto                   2                    1.48          Drama  
3         Crypto                   2                    0.35         Horror  
4         Crypto                   2                    0.13         Action

In [85]:
# Obtener un resumen del dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   customer_id             5000 non-null   object 
 1   age                     5000 non-null   int64  
 2   gender                  5000 non-null   object 
 3   subscription_type       5000 non-null   object 
 4   watch_hours             5000 non-null   float64
 5   last_login_days         5000 non-null   int64  
 6   region                  5000 non-null   object 
 7   device                  5000 non-null   object 
 8   monthly_fee             5000 non-null   float64
 9   churned                 5000 non-null   int64  
 10  payment_method          5000 non-null   object 
 11  number_of_profiles      5000 non-null   int64  
 12  avg_watch_time_per_day  5000 non-null   float64
 13  favorite_genre          5000 non-null   object 
dtypes: float64(3), int64(4), object(7)
memor

In [81]:
# obtener los datos faltantes
df.isnull().sum()

customer_id               0
age                       0
gender                    0
subscription_type         0
watch_hours               0
last_login_days           0
region                    0
device                    0
monthly_fee               0
churned                   0
payment_method            0
number_of_profiles        0
avg_watch_time_per_day    0
favorite_genre            0
dtype: int64

In [87]:
# Mostrar las dimensiones
print(df.shape)

(5000, 14)


In [89]:
# Filtrar los jóvenes que contengan únicamente a los usuarios que tengan 25 años o menos
df_jovenes = df[df['age'] <= 25]
df_jovenes.head()

customer_id  age  gender subscription_type  \
19  a088d61d-be5a-409e-b943-73b145b358d1   21  Female          Standard   
26  6e061f35-b1b5-4efe-9e37-f40a14d929b1   24    Male           Premium   
32  e62d9bc8-dab9-42e0-b6b2-e8d076fe843b   23  Female           Premium   
37  839ec473-5f41-4a8b-955a-ec14b3a9cad4   22  Female          Standard   
39  aa97d1a3-c4ad-4c76-bd2a-56f1b46a753c   19    Male          Standard   

    watch_hours  last_login_days         region   device  monthly_fee  \
19        15.53               27  South America   Laptop        13.99   
26         6.92               13         Africa  Desktop        17.99   
32        13.31               34         Africa   Mobile        17.99   
37         9.69               35           Asia       TV        13.99   
39         4.34                1           Asia   Tablet        13.99   

    churned payment_method  number_of_profiles  avg_watch_time_per_day  \
19        0    Credit Card                   1                    0.55   
26        0         Crypto                   2                    0.49   
32        1     Debit Card                   2                    0.38   
37        1         Crypto                   4                    0.27   
39        0         PayPal                   1                    2.17   

   favorite_genre  
19         Comedy  
26         Action  
32        Romance  
37    Documentary  
39         Sci-Fi

In [93]:
print(f"Se encontraron {len(df_jovenes)} jovenes menores 0 igual a 25 años")

Se encontraron 801 jovenes menores 0 igual a 25 años


In [96]:
condicion_1 = df['subscription_type'] == 'premium'
condicion_2 = df['churned'] == 0
clientes_leales = condicion_1 & condicion_2
clientes_leales

0       False
1       False
2       False
3       False
4       False
        ...  
4995    False
4996    False
4997    False
4998    False
4999    False
Length: 5000, dtype: bool