# Ejercicio 1: Matriz de Calificaciones

### 1. Usa `np.array` para crear una matriz `notas` con las calificaciones de 4 estudiantes en 3 exámenes:
$$
\begin{bmatrix}
 8 & 7 & 9 \\
 6 & 5 & 7 \\
 9 & 8 & 10 \\
 7 & 6 & 8
\end{bmatrix}
$$

In [2]:
import numpy as np

calificaciones = np.array([
    [8, 7, 9],
    [6, 5, 7],
    [9, 8, 10],
    [7, 6, 8]
])

print(calificaciones)

[[ 8  7  9]
 [ 6  5  7]
 [ 9  8 10]
 [ 7  6  8]]


### 2. Calcula:
- Promedio de cada estudiante (promedio por fila).
- Promedio de cada examen (promedio por columna).

In [3]:
# axis = 0 --> columnas, axis = 1 --> filas
promedio_estudiantes_fila = np.mean(calificaciones, axis=1)
print(f"Promedio de cada estudiante por fila: {promedio_estudiantes_fila}")

promedio_estudiantes_columna = np.mean(calificaciones, axis=0)
print(f"Promedio de cada estudiante por columna: {promedio_estudiantes_columna}")

Promedio de cada estudiante por fila: [8. 6. 9. 7.]
Promedio de cada estudiante por columna: [7.5 6.5 8.5]


### 3. Extrae (slice) la columna del **segundo examen.**

In [4]:
columna_2do_examen = calificaciones[:, 1]
print(f"Columna del segundo examen: {columna_2do_examen}")

Columna del segundo examen: [7 5 8 6]


### 4. Crea un nuevo arreglo con las notas **mayores o iguales a 8.**

In [5]:
notas_mayor_igual_8 = calificaciones[calificaciones >= 8]
print(f"Notas mayores o iguales a 8: {notas_mayor_igual_8}")

Notas mayores o iguales a 8: [ 8  9  9  8 10  8]


# Ejercicio 2: Estadísticas Básicas de Ventas

### 1. Crear el arreglo `ventas` con los valores:
`[12, 15, 8, 20, 5, 18, 10]`

In [6]:
ventas = np.array([12, 15, 8, 20, 5, 18, 10])
print(f"Array de ventas: {ventas}")

Array de ventas: [12 15  8 20  5 18 10]


### 2. Calcula:
- Venta total (`sum`)
- Venta promedio (`mean`)
- Venta máxima y mínima (`max`, `min`)

In [7]:
venta_total = ventas.sum()
venta_promedio = ventas.mean()
venta_maxima = ventas.max()
venta_minima = ventas.min()

print(f"Venta total: {venta_total}")
print(f"Venta promedio: {venta_promedio}")
print(f"Venta máxima: {venta_maxima}")
print(f"Venta mínima: {venta_minima}")

Venta total: 88
Venta promedio: 12.571428571428571
Venta máxima: 20
Venta mínima: 5


### 3. Crea un nuevo arreglo `mayores_promedio` con solo las ventas **mayores al promedio.**

In [8]:
mayores_promedio = ventas[ventas > venta_promedio]
print(f"Ventas mayores al promedio: {mayores_promedio}")

Ventas mayores al promedio: [15 20 18]


### 4. Ordenar el arreglo `ventas` de menor a mayor

In [9]:
ordenado_menor_mayor = np.sort(ventas)
print(f"Ventas ordenadas de menor a mayor: {ordenado_menor_mayor}")

Ventas ordenadas de menor a mayor: [ 5  8 10 12 15 18 20]
